In [85]:
import pandas as pd
import numpy as np

In [86]:
grid = np.zeros( (45, 45) )

In [87]:
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [88]:
grid2 = np.zeros( (45, 45) )
for ren in range(45):
    for col in range(45):
        grid2[ren][col] = 20
grid2

array([[20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.],
       ...,
       [20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.],
       [20., 20., 20., ..., 20., 20., 20.]])

In [89]:
for ren in range(45):
        for col in range(45):
            grid2[ren][col] += 1
grid2

array([[21., 21., 21., ..., 21., 21., 21.],
       [21., 21., 21., ..., 21., 21., 21.],
       [21., 21., 21., ..., 21., 21., 21.],
       ...,
       [21., 21., 21., ..., 21., 21., 21.],
       [21., 21., 21., ..., 21., 21., 21.],
       [21., 21., 21., ..., 21., 21., 21.]])

In [90]:
celda0 = grid2[0][0]
celda0

21.0

In [91]:
for ren in range(45):
        for col in range(45):
            grid2[ren][col] += 1
grid2

array([[22., 22., 22., ..., 22., 22., 22.],
       [22., 22., 22., ..., 22., 22., 22.],
       [22., 22., 22., ..., 22., 22., 22.],
       ...,
       [22., 22., 22., ..., 22., 22., 22.],
       [22., 22., 22., ..., 22., 22., 22.],
       [22., 22., 22., ..., 22., 22., 22.]])

In [92]:
celda1 = grid2[1][1]
celda1

22.0

In [93]:
for i in range(15):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [94]:
import random

In [95]:
print(random.choice([0,1]))

1


In [222]:
def uno():
    if 1 == 1:
        print(1)
        return True
    else:
        return False

def dos():
    if 2 == 2:
        print(2)
        return True
    else:
        return False

def tres():
    if 3 == 3:
        print(3)
        return True
    else:
        return False

def cuatro():
    if 4 == 4:
        print(4)
        return True
    else:
        return False

def cinco():
    print(5)


def elegirCamino(options):
    elements = len(options)
    if elements != 0:
        choice = random.choice(options)
        completed = True
        if choice == 1:
            task = uno()
            if task != completed:
                options.remove(1)
                elegirCamino(options)
        if choice == 2:
            task = dos()
            if task != completed:
                options.remove(2)
                elegirCamino(options)
        if choice == 3:
            task = tres()
            if task != completed:
                options.remove(3)
                elegirCamino(options)
        if choice == 4:
            task = cuatro()
            if task != completed:
                options.remove(4)
                elegirCamino(options)
    else:
        cinco()

def camino():
    list1 = [1,2,3,4]
    elegirCamino(list1)

camino()
print("Cosas despues de la función")

4
Cosas despues de la función
