In [385]:
import pandas as pd
import numpy as np

In [386]:
grid = np.zeros( (4, 5) )

In [387]:
grid

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [388]:
grid2 = np.zeros( (5, 5) )
for ren in range(5):
    for col in range(5):
        grid2[ren][col] = 20
grid2

array([[20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.],
       [20., 20., 20., 20., 20.]])

In [389]:
for ren in range(5):
    for col in range(5):
        grid2[ren][col] += 1
grid2

array([[21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.]])

In [390]:
celda0 = grid2[0][0]
celda0

21.0

In [391]:
grid2[0][0] -= 5
grid2

array([[16., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.],
       [21., 21., 21., 21., 21.]])

In [392]:
celda1 = grid2[1][1]
celda1

21.0

In [393]:
for i in range(15):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14


In [394]:
import random

In [395]:
print(random.choice([0,1]))

0


In [396]:
def uno():
    if 1 == 1:
        print(1)
        return True
    else:
        return False

def dos():
    if 2 == 2:
        print(2)
        return True
    else:
        return False

def tres():
    if 3 == 3:
        print(3)
        return True
    else:
        return False

def cuatro():
    if 4 == 4:
        print(4)
        return True
    else:
        return False

def cinco():
    print(5)


def elegirCamino(options):
    elements = len(options)
    if elements != 0:
        choice = random.choice(options)
        completed = True
        if choice == 1:
            task = uno()
            if task != completed:
                options.remove(1)
                elegirCamino(options)
        if choice == 2:
            task = dos()
            if task != completed:
                options.remove(2)
                elegirCamino(options)
        if choice == 3:
            task = tres()
            if task != completed:
                options.remove(3)
                elegirCamino(options)
        if choice == 4:
            task = cuatro()
            if task != completed:
                options.remove(4)
                elegirCamino(options)
    else:
        cinco()

def camino():
    list1 = [1,2,3,4]
    elegirCamino(list1)

camino()
print("Cosas despues de la función")

3
Cosas despues de la función


In [397]:
operacion1 = 155//2
print(operacion1)
operacion2 = 155/2
print(operacion2)

77
77.5


In [398]:
x = random.randint(0,35)
x

24

In [399]:
posibleDirections = (1,2,3,4)
len(posibleDirections)

4

In [400]:
posibleDirections = (1,2,3,4)
tempList = list(posibleDirections)
tempList.remove(2)
outTuple = tuple(tempList)
outTuple

(1, 3, 4)

In [401]:
posibleDirections = ()
elements = len(posibleDirections)
print(elements)
if elements != 0:
    choice = np.random.choice(posibleDirections)
    print(choice)
else:
    print("No hay elementos")

0
No hay elementos


In [404]:
elemento = 9
limite = 10
if elemento+1 <= limite:
    print("Se puede mover")
else:
    print("No se puede mover")

No se puede mover


In [406]:
elemento = 0
limite = 0
if elemento-1 >= limite:
    print("Se puede mover")
else:
    print("No se puede mover")

No se puede mover


In [409]:
if 11 <= 10:
    print("True")
else:
    print("False")

False


In [412]:
if -1 >= 0:
    print("True")
else:
    print("False")

False
